### ISSUE TITLE
Implement versioning

### ISSUE THREAD

**Issue by tolomaus** [BMC-RLM/brpm_content#4]
Implement versioning of the framework as well as the modules.

Make it possible to install multiple versions at the same time to allow consumers of the version some time to migrate to a next version without blocking other consumers who want to upgrade to the next version

Allow specifying the version number when creaing dependencies on the framework as well as the modules

Automatically install any dependencies when a module is installed

**Comment by tolomaus** [comment]
Looked at the RubyGems platform that we could use for this feature (and wrap all modules as gems).

1) gem server (local or remote) to store the modules
2) gem specs to define meta data and module dependencies
3) gem cli to install a module with all of its dependencies 
4) gem ruby hooks to load and require the modules at run time when needed

At least the load and require item will not work with the current implementation of BRPM as all gems must be defined in BRPM's Gemfile before they can be used inside of automation scripting.

The alternative is to stick with the already implemented load and require logic on top the other items.

**Comment by jthokie** [comment]
When we add support for shell script automations, will the gem method still work for packaging?

**Comment by tolomaus** [comment]
Good question. I would say as long as its ruby code which will trigger the shell scripts them the gem solution should work. A gem can contain .sh files just like any other file type. The ruby code will just have to find the exact script based on some convention or configuration.

@bradybyrd @bfarrell is there any info available yet on how the shell script automations will/should work?

**Comment by bfarrell** [comment]
I can share the SDD on how it will work.  Implementation changed it a bit.  However, we could meet and discuss.

**Comment by tolomaus** [comment]
Cool, let me first finish up this gemification experiment so we can discuss it (and its implications) in its entirety

**Comment by bradybyrd** [comment]
Niek,
  You can test them on vpn.  I have latest 4.8 build on 10.20.12.23:8080/brpm.

The design works similar to the transport and dispatch layers in the framework.  The key difference is that the shell script can be stored in brpm.  The script type (shell) and the server os type determine the wrapper script companion that gets transported to the target.
B

Bradford Byrd
Bradford.Byrd@gmail.com
603.361.6198
